### ISSUE TITLE
Camera flipping on android, especially when screen locked

### ISSUE THREAD

**Issue by andibuch** [WMSPanel/larix-testing#2]
ISSUE:
I've had this issue happen a lot:

1. Start video in horizontal-mode
2. Go to play a set
3. Come back, watch the video back, and find it is completely destroyed

"Destroyed," in this case, meaning that the video has now been rotated vertically on its side, surrounded by two giant black bars

So, not only is it now streaming rotated, but I can't even fix it in post – since it's effectively broadcasting *AND* saving at an effective resolution of 1080 x 607, instead of the 1920 x 1080 chosen

This.  Drives.  Me.  *INSANE*

It seems to happen more frequently if I enable "Background streaming" and then turn my display off, to save battery.  But it seems to sometimes just randomly happen, even if the screen is kept on.

I've tried everything I can think of.  I've even tried using external apps to lock the rotation of my phone in horizontal mode.  Same bullsh*t.

SOLUTION:
Please.  P L E A S E.  Just add a "rotation lock" feature??

A feature that, once you start a stream, keeps both the broadcast *AND* the video-feed-within-the-broadcast locked in the same orientations as started???

I already have "Live rotation" turned off, but this does nothing for the actual camera feed, apparently; I don't know if it's entirely broken, or maybe it just stops the broadcast resolution from changing when rotated.  But.  Please.  Fix.  This

**Comment by andibuch** [comment]
Okay, upon further research, I've figured out the following:

Port left, no external rotation app:
	Flips when screen unlocks

Port right, no external rotation app:
	Does not flip

Port right, orientation locked with Rotation Control:
	Rotates CW INSTANTLY

Port left, orientation locked with Rotation Control:
	Flips when screen unlocks

So, it *seems* that, if I *do not* use an external rotation control app, and I *make sure* that the port is oriented towards the right when I start the video... I will be okay

However, if it's oriented towards the left, I'll be okay if I keep the screen on – but if I lock the screen, then it will flip upside-down when I unlock the screen

And if I use an external app to keep the phone locked in a particular orientation, it only makes things *infinitely* worse

**Comment by WMSPanel** [comment]
We can see your message to our helpdesk about this so we'll respond there. Thank you.
