### ISSUE TITLE
Local Copy Not Saved When Phone Dies

### ISSUE THREAD

**Issue by andibuch** [WMSPanel/larix-testing#3]
There have been many times I've done a long stream and run my battery down to the point where it dies

When this happens, the local copy ends up trashed.  I end up with a 2+ GB file, that I *cannot* open in any external app

My asks:

1. Is there a way to open / fix / restore / salvage / extract video from these incomplete files that weren't ended properly?
2. Can you implement a feature that either: a) creates videos that don't need to be finalized, or b) stops and saves the video when the phone battery is critically low?

Thanks!

**Comment by WMSPanel** [comment]
We can see your message to our helpdesk about this so we'll respond there. Thank you.
